trigger:
  branches:
    include:
      - main

jobs:
- job: CloneAndPush
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: none  # Skip the default checkout

  - script: |
      echo "Cloning the GitHub repository..."
      git clone https://github.com/shatterhats/WebGoatNew.git
      git checkout azure-pipelines